Added Marshal
nodes-ios/SerpentPerformanceComparison pull request #8
Opened 2017-03-07 14:36 UTC by bre7

2017-03-07 14:46 UTC, nickskull commented on SerpentComparison.xcodeproj/project.pbxproj
> +		245AA8C71E6EF3E000C91BD7 /* Marshal.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 245AA8C51E6EF3E000C91BD7 /* Marshal.framework */; };
Somehow the file got added twice. Can you double check it's not added twice in the build phases? :)

2017-03-07 14:51 UTC, bre7 commented on SerpentComparison.xcodeproj/project.pbxproj
> +		245AA8C71E6EF3E000C91BD7 /* Marshal.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 245AA8C51E6EF3E000C91BD7 /* Marshal.framework */; };
👍

2017-03-07 17:23 UTC, dominik-hadl approved these changes

2017-03-07 20:21 UTC, mariusc requested changes
Looks good overall. I only had one change request. The results so far seem impressive. Looking forward to merging this, and I'll update the readme afterwards.

[Later Edit]: I just realised I managed to comment on an outdated diff 🤦‍♂️ . However, the issue is still there. Hope it makes sense 😄

2017-03-07 20:21 UTC, mariusc commented on SerpentComparisonTests/SerpentComparisonTests.swift
> +                let _ : [PerformanceTestModel] = try smallMarshalDict.value(for: "data")
This needs to be `[PerformanceTestSmallModel]`

2017-03-07 20:40 UTC, bre7 commented on SerpentComparisonTests/SerpentComparisonTests.swift
> +                let _ : [PerformanceTestModel] = try smallMarshalDict.value(for: "data")
My bad !

2017-03-07 20:42 UTC, bre7 commented
One more thing, can I also push a new version of setUp() ?

```swift
var largeData: Data!
    var smallData: Data!
    
    override func setUp() {
        super.setUp()

        let bundle = Bundle(for: type(of: self))
        if let path = bundle.url(forResource: "PerformanceTest", withExtension: "json"),
            let data = try? Data(contentsOf: path) {
            largeData = data
        }
        if let path = bundle.url(forResource: "PerformanceSmallTest", withExtension: "json"),
            let data = try? Data(contentsOf: path) {
            smallData = data
        }
    }
```

To avoid NSData -> Data casting inside each method.

2017-03-07 20:49 UTC, bre7 commented on SerpentComparisonTests/SerpentComparisonTests.swift
> +                let _ : [PerformanceTestModel] = try smallMarshalDict.value(for: "data")
Use XCTFail instead of print ?

2017-03-07 20:52 UTC, nickskull commented
@bre7 I agree, makes sense not to cast it everywhere. However, let's make that another PR as it's not related to adding Marshal :)

2017-03-07 20:58 UTC, mariusc approved these changes

2017-03-07 20:59 UTC, mariusc commented
Thanks; waiting for Travis to build successfully then we'll merge.

2017-03-07 22:33 UTC, bre7 commented
I avoided using custom operators, but for the record (and your README), Marshal does provide one `<|`

2017-03-08 01:07 UTC, merged

2017-03-08 01:08 UTC, nickskull commented
@bre7 Thanks for the PR, merged it now 🌮 🎉

2017-03-08 01:10 UTC, bre7 commented
Awesome ! I submitted a new one 🤓